name: auth
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  
  firebase_auth: ^4.9.0

  json_serializable: ^6.7.1

  json_annotation: ^4.8.1

  google_sign_in: ^6.1.5
  
  firebase_core: ^2.16.0
  
  flutter_facebook_auth: ^6.0.2

  cloud_firestore: ^4.9.2





dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.1
  build_runner: ^2.4.6
